# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Mt Security
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer as create_point_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_mt.tasks import sitrep_table as sitrep_table

# %% [markdown]
# ## Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ## Extract Timezone

# %%
# parameters

get_timezone_params = dict()

# %%
# call the task


get_timezone = (
    get_timezone_from_time_range.set_task_instance_id("get_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_range=time_range, **get_timezone_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Get Illegal Events

# %%
# parameters

get_event_data_params = dict(
    event_types=...,
)

# %%
# call the task


get_event_data = (
    get_events.set_task_instance_id("get_event_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        time_range=time_range,
        event_columns=None,
        raise_on_empty=False,
        include_details=True,
        include_updates=False,
        include_related_events=False,
        include_display_values=True,
        include_null_geometry=True,
        **get_event_data_params,
    )
    .call()
)


# %% [markdown]
# ## Convert to Timezone

# %%
# parameters

convert_tz_params = dict()

# %%
# call the task


convert_tz = (
    convert_values_to_timezone.set_task_instance_id("convert_tz")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=get_event_data, timezone=get_timezone, columns=["time"], **convert_tz_params
    )
    .call()
)


# %% [markdown]
# ## Filter Event Coordinates

# %%
# parameters

filter_events_params = dict(
    bounding_box=...,
)

# %%
# call the task


filter_events = (
    apply_reloc_coord_filter.set_task_instance_id("filter_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=convert_tz,
        roi_gdf=None,
        roi_name=None,
        reset_index=False,
        filter_point_coords=[
            {"x": 180.0, "y": 90.0},
            {"x": 0.0, "y": 0.0},
            {"x": 1.0, "y": 1.0},
        ],
        **filter_events_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize Event Details

# %%
# parameters

normalize_event_details_params = dict()

# %%
# call the task


normalize_event_details = (
    normalize_json_column.set_task_instance_id("normalize_event_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_events,
        column="event_details",
        skip_if_not_exists=True,
        sort_columns=False,
        **normalize_event_details_params,
    )
    .call()
)


# %% [markdown]
# ## Remove Event Details Prefix

# %%
# parameters

drop_details_prefix_params = dict()

# %%
# call the task


drop_details_prefix = (
    drop_column_prefix.set_task_instance_id("drop_details_prefix")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=normalize_event_details,
        prefix="event_details__",
        duplicate_strategy="suffix",
        **drop_details_prefix_params,
    )
    .call()
)


# %% [markdown]
# ## Generate SITREP Table

# %%
# parameters

sitrep_data_params = dict()

# %%
# call the task


sitrep_data = (
    sitrep_table.set_task_instance_id("sitrep_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=drop_details_prefix, **sitrep_data_params)
    .call()
)


# %% [markdown]
# ## Events Colormap

# %%
# parameters

events_colormap_params = dict()

# %%
# call the task


events_colormap = (
    apply_color_map.set_task_instance_id("events_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=drop_details_prefix,
        input_column_name="event_type",
        colormap="Dark2",
        output_column_name="event_type_colormap",
        **events_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Set Map Title

# %%
# parameters

set_map_title_params = dict()

# %%
# call the task


set_map_title = (
    set_string_var.set_task_instance_id("set_map_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Security Report Locations", **set_map_title_params)
    .call()
)


# %% [markdown]
# ## Base Maps

# %%
# parameters

base_map_defs_params = dict(
    base_maps=...,
)

# %%
# call the task


base_map_defs = (
    set_base_maps.set_task_instance_id("base_map_defs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_map_defs_params)
    .call()
)


# %% [markdown]
# ## Rename Columns for Display

# %%
# parameters

rename_display_cols_params = dict()

# %%
# call the task


rename_display_cols = (
    map_columns.set_task_instance_id("rename_display_cols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=events_colormap,
        drop_columns=[],
        retain_columns=[],
        raise_if_not_found=False,
        rename_columns={
            "time": "Event Time",
            "event_type": "Event Type",
            "serial_number": "Serial Number",
        },
        **rename_display_cols_params,
    )
    .call()
)


# %% [markdown]
# ## Create Point Layer

# %%
# parameters

event_point_layer_params = dict(
    zoom=...,
)

# %%
# call the task


event_point_layer = (
    create_point_layer.set_task_instance_id("event_point_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
            all_geometry_are_none,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=rename_display_cols,
        layer_style={"fill_color_column": "event_type_colormap", "get_radius": 5},
        legend={"label_column": "Event Type", "color_column": "event_type_colormap"},
        tooltip_columns=["Serial Number", "Event Time", "Event Type"],
        **event_point_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Ecomap

# %%
# parameters

event_ecomap_params = dict(
    view_state=...,
    widget_id=...,
)

# %%
# call the task


event_ecomap = (
    draw_ecomap.set_task_instance_id("event_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geo_layers=event_point_layer,
        title=None,
        tile_layers=base_map_defs,
        north_arrow_style={"placement": "top-left"},
        legend_style={
            "title": "Event Type",
            "format_title": False,
            "placement": "bottom-right",
        },
        static=False,
        max_zoom=20,
        **event_ecomap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Ecomap

# %%
# parameters

ecomap_html_url_params = dict(
    filename=...,
)

# %%
# call the task


ecomap_html_url = (
    persist_text.set_task_instance_id("ecomap_html_url")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=event_ecomap,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="illegal_events_map",
        **ecomap_html_url_params,
    )
    .call()
)


# %% [markdown]
# ## Create Map Widget

# %%
# parameters

map_widget_params = dict(
    view=...,
)

# %%
# call the task


map_widget = (
    create_map_widget_single_view.set_task_instance_id("map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title=set_map_title, data=ecomap_html_url, **map_widget_params)
    .call()
)


# %% [markdown]
# ## Set Table Title

# %%
# parameters

set_table_title_params = dict()

# %%
# call the task


set_table_title = (
    set_string_var.set_task_instance_id("set_table_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Security Reports", **set_table_title_params)
    .call()
)


# %% [markdown]
# ## Draw SITREP Table

# %%
# parameters

sitrep_html_table_params = dict()

# %%
# call the task


sitrep_html_table = (
    draw_table.set_task_instance_id("sitrep_html_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=sitrep_data,
        columns=[
            "Date",
            "Type",
            "Comments",
            "Number of People",
            "Place of Origin",
            "Sex",
            "Details",
        ],
        table_config={"enable_sorting": True},
        widget_id=set_table_title,
        **sitrep_html_table_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Table HTML

# %%
# parameters

persist_table_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_table_html = (
    persist_text.set_task_instance_id("persist_table_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=sitrep_html_table,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="sitrep_table",
        **persist_table_html_params,
    )
    .call()
)


# %% [markdown]
# ## Create Table Widget

# %%
# parameters

table_widget_params = dict(
    view=...,
)

# %%
# call the task


table_widget = (
    create_table_widget_single_view.set_task_instance_id("table_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title=set_table_title, data=persist_table_html, **table_widget_params)
    .call()
)


# %% [markdown]
# ## Persist SITREP CSV

# %%
# parameters

persist_sitrep_csv_params = dict(
    filename=...,
)

# %%
# call the task


persist_sitrep_csv = (
    persist_df_wrapper.set_task_instance_id("persist_sitrep_csv")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        df=sitrep_data,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="sitrep",
        filetypes=["csv"],
        sanitize=False,
        **persist_sitrep_csv_params,
    )
    .call()
)


# %% [markdown]
# ## Create Security Report

# %%
# parameters

sitrep_report_params = dict(
    template_path=...,
)

# %%
# call the task


sitrep_report = (
    create_docx.set_task_instance_id("sitrep_report")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        groupers=None,
        context={
            "items": [
                {
                    "item_type": "timerange",
                    "key": "report_date",
                    "value": time_range,
                    "format": "%b %Y",
                },
                {
                    "item_type": "image",
                    "key": "event_map",
                    "value": ecomap_html_url,
                    "screenshot_config": {
                        "wait_for_timeout": 1000,
                        "max_concurrent_pages": 2,
                        "device_scale_factor": 1.0,
                    },
                },
                {"item_type": "table", "key": "summary", "value": sitrep_data},
            ]
        },
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="mt_security_report",
        **sitrep_report_params,
    )
    .call()
)


# %% [markdown]
# ## Create Dashboard

# %%
# parameters

dashboard_params = dict(
    groupers=...,
    warning=...,
)

# %%
# call the task


dashboard = (
    gather_dashboard.set_task_instance_id("dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[map_widget, table_widget],
        time_range=time_range,
        **dashboard_params,
    )
    .call()
)
