# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer as create_point_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_mt.tasks import sitrep_table as sitrep_table

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "get_timezone": ["time_range"],
        "get_event_data": [],
        "convert_tz": ["get_event_data", "get_timezone"],
        "filter_events": ["convert_tz"],
        "normalize_event_details": ["filter_events"],
        "drop_details_prefix": ["normalize_event_details"],
        "sitrep_data": ["drop_details_prefix"],
        "events_colormap": ["drop_details_prefix"],
        "set_map_title": [],
        "base_map_defs": [],
        "rename_display_cols": ["events_colormap"],
        "event_point_layer": ["rename_display_cols"],
        "event_ecomap": ["event_point_layer", "base_map_defs"],
        "ecomap_html_url": ["event_ecomap"],
        "map_widget": ["set_map_title", "ecomap_html_url"],
        "set_table_title": [],
        "sitrep_html_table": ["sitrep_data", "set_table_title"],
        "persist_table_html": ["sitrep_html_table"],
        "table_widget": ["set_table_title", "persist_table_html"],
        "persist_sitrep_csv": ["sitrep_data"],
        "sitrep_report": ["time_range", "ecomap_html_url", "sitrep_data"],
        "dashboard": ["workflow_details", "map_widget", "table_widget", "time_range"],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "get_event_data": Node(
            async_task=load_df.validate()
            .set_task_instance_id("get_event_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "deserialize_json": False,
            }
            | (params_dict.get("get_event_data") or {}),
            method="call",
        ),
        "convert_tz": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("convert_tz")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("get_event_data"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "time",
                ],
            }
            | (params_dict.get("convert_tz") or {}),
            method="call",
        ),
        "filter_events": Node(
            async_task=apply_reloc_coord_filter.validate()
            .set_task_instance_id("filter_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_tz"),
                "roi_gdf": None,
                "roi_name": None,
                "reset_index": False,
                "filter_point_coords": [
                    {
                        "x": 180.0,
                        "y": 90.0,
                    },
                    {
                        "x": 0.0,
                        "y": 0.0,
                    },
                    {
                        "x": 1.0,
                        "y": 1.0,
                    },
                ],
            }
            | (params_dict.get("filter_events") or {}),
            method="call",
        ),
        "normalize_event_details": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_event_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_events"),
                "column": "event_details",
                "skip_if_not_exists": True,
                "sort_columns": False,
            }
            | (params_dict.get("normalize_event_details") or {}),
            method="call",
        ),
        "drop_details_prefix": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_details_prefix")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("normalize_event_details"),
                "prefix": "event_details__",
                "duplicate_strategy": "suffix",
            }
            | (params_dict.get("drop_details_prefix") or {}),
            method="call",
        ),
        "sitrep_data": Node(
            async_task=sitrep_table.validate()
            .set_task_instance_id("sitrep_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_details_prefix"),
            }
            | (params_dict.get("sitrep_data") or {}),
            method="call",
        ),
        "events_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("events_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_details_prefix"),
                "input_column_name": "event_type",
                "colormap": "Dark2",
                "output_column_name": "event_type_colormap",
            }
            | (params_dict.get("events_colormap") or {}),
            method="call",
        ),
        "set_map_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_map_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Illegal Events Map",
            }
            | (params_dict.get("set_map_title") or {}),
            method="call",
        ),
        "base_map_defs": Node(
            async_task=set_base_maps.validate()
            .set_task_instance_id("base_map_defs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_map_defs") or {}),
            method="call",
        ),
        "rename_display_cols": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_display_cols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events_colormap"),
                "raise_if_not_found": False,
                "rename_columns": {
                    "time": "Event Time",
                    "event_type": "Event Type",
                    "serial_number": "Serial Number",
                },
            }
            | (params_dict.get("rename_display_cols") or {}),
            method="call",
        ),
        "event_point_layer": Node(
            async_task=create_point_layer.validate()
            .set_task_instance_id("event_point_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                    all_geometry_are_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("rename_display_cols"),
                "layer_style": {
                    "fill_color_column": "event_type_colormap",
                    "get_radius": 5,
                },
                "legend": {
                    "label_column": "Event Type",
                    "color_column": "event_type_colormap",
                },
                "tooltip_columns": [
                    "Serial Number",
                    "Event Time",
                    "Event Type",
                ],
            }
            | (params_dict.get("event_point_layer") or {}),
            method="call",
        ),
        "event_ecomap": Node(
            async_task=draw_ecomap.validate()
            .set_task_instance_id("event_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geo_layers": DependsOn("event_point_layer"),
                "title": None,
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {
                    "placement": "top-left",
                },
                "legend_style": {
                    "title": "Event Type",
                    "format_title": False,
                    "placement": "bottom-right",
                },
                "static": False,
                "max_zoom": 20,
            }
            | (params_dict.get("event_ecomap") or {}),
            method="call",
        ),
        "ecomap_html_url": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("ecomap_html_url")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("event_ecomap"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "illegal_events_map",
            }
            | (params_dict.get("ecomap_html_url") or {}),
            method="call",
        ),
        "map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_map_title"),
                "data": DependsOn("ecomap_html_url"),
            }
            | (params_dict.get("map_widget") or {}),
            method="call",
        ),
        "set_table_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_table_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "SITREP Summary",
            }
            | (params_dict.get("set_table_title") or {}),
            method="call",
        ),
        "sitrep_html_table": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("sitrep_html_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("sitrep_data"),
                "columns": [
                    "Date",
                    "Type",
                    "Comments",
                    "Number of People",
                    "Place of Origin",
                    "Sex",
                    "Details",
                ],
                "table_config": {
                    "enable_sorting": True,
                },
                "widget_id": DependsOn("set_table_title"),
            }
            | (params_dict.get("sitrep_html_table") or {}),
            method="call",
        ),
        "persist_table_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_table_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("sitrep_html_table"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "sitrep_table",
            }
            | (params_dict.get("persist_table_html") or {}),
            method="call",
        ),
        "table_widget": Node(
            async_task=create_table_widget_single_view.validate()
            .set_task_instance_id("table_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_table_title"),
                "data": DependsOn("persist_table_html"),
            }
            | (params_dict.get("table_widget") or {}),
            method="call",
        ),
        "persist_sitrep_csv": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_sitrep_csv")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("sitrep_data"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "sitrep",
                "filetypes": [
                    "csv",
                ],
                "sanitize": False,
            }
            | (params_dict.get("persist_sitrep_csv") or {}),
            method="call",
        ),
        "sitrep_report": Node(
            async_task=create_docx.validate()
            .set_task_instance_id("sitrep_report")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "context": {
                    "items": [
                        {
                            "item_type": "timerange",
                            "key": "report_date",
                            "value": DependsOn("time_range"),
                            "format": "%b %Y",
                        },
                        {
                            "item_type": "image",
                            "key": "event_map",
                            "value": DependsOn("ecomap_html_url"),
                            "screenshot_config": {
                                "wait_for_timeout": 1000,
                                "max_concurrent_pages": 2,
                                "device_scale_factor": 1.0,
                            },
                        },
                        {
                            "item_type": "table",
                            "key": "summary",
                            "value": DependsOn("sitrep_data"),
                        },
                    ],
                },
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "mt_security_report",
            }
            | (params_dict.get("sitrep_report") or {}),
            method="call",
        ),
        "dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("map_widget"),
                    DependsOn("table_widget"),
                ],
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
