# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: str | None = Field("", title="Workflow Description")


class GetEventData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_types: list[str] = Field(
        ...,
        description="Illegal event types to include in the SITREP report.",
        title="Event Types",
    )


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps1(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps6(BaseModel):
    url: (
        constr(
            pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)"
        )
        | None
    ) = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: int | None = Field(
        None,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: int | None = Field(
        None,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class BaseMapDefs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: (
        list[
            BaseMaps
            | BaseMaps1
            | BaseMaps2
            | BaseMaps3
            | BaseMaps4
            | BaseMaps5
            | BaseMaps6
        ]
        | None
    ) = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title=" ",
    )


class GenerateMap(BaseModel):
    base_map_defs: BaseMapDefs | None = Field(None, title="Base Maps")


class BaseMapDefs1(BaseModel):
    base_maps: Any | None = [
        {
            "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
            "opacity": 1,
        }
    ]


class Filetype(Enum):
    csv = "csv"


class PersistSitrepCsv(BaseModel):
    filetypes: list[Filetype] | None = ["csv"]


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class BoundingBox(BaseModel):
    min_y: float | None = Field(-90.0, title="Min Latitude")
    max_y: float | None = Field(90.0, title="Max Latitude")
    min_x: float | None = Field(-180.0, title="Min Longitude")
    max_x: float | None = Field(180.0, title="Max Longitude")


class TableConfig(BaseModel):
    enable_sorting: bool | None = Field(True, title="Enable Sorting")
    enable_filtering: bool | None = Field(False, title="Enable Filtering")
    enable_download: bool | None = Field(False, title="Enable Download")
    hide_header: bool | None = Field(False, title="Hide Header")


class AllGrouper(BaseModel):
    index_name: str | None = Field("All", title="Index Name")


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalIndex(str, Enum):
    Year__example__2024_ = "%Y"
    Month__example__September_ = "%B"
    Year_and_Month__example__2023_01_ = "%Y-%m"
    Day_of_the_year_as_a_number__example__365_ = "%j"
    Day_of_the_month_as_a_number__example__31_ = "%d"
    Day_of_the_week__example__Sunday_ = "%A"
    Hour__24_hour_clock__as_number__example__22_ = "%H"
    Date__example__2025_01_31_ = "%Y-%m-%d"


class TemporalGrouper(BaseModel):
    temporal_index: TemporalIndex = Field(..., title="Time")


class ValueGrouper(BaseModel):
    index_name: str = Field(..., title="Category")


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: TimezoneInfo | None = Field(None, title="Timezone")


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class FilterEvents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bounding_box: BoundingBox | None = Field(
        default_factory=lambda: BoundingBox.model_validate(
            {"min_x": 33.0, "min_y": -3.0, "max_x": 36.0, "max_y": 0.0}
        ),
        description="Filter events to inside these bounding coordinates.",
        title="Bounding Box",
    )


class ProcessEvents(BaseModel):
    filter_events: FilterEvents | None = Field(None, title="Filter Event Coordinates")


class SitrepHtmlTable(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    columns: list[str] | None = Field(
        None,
        description="The list of dataframe columns to render in the table. Leave empty to render all columns",
        title="Columns",
    )
    table_config: TableConfig | None = Field(
        None, description="Configuration options for the table.", title="Table Config"
    )


class SITREPTableDisplay(BaseModel):
    sitrep_html_table: SitrepHtmlTable | None = Field(None, title="Draw SITREP Table")


class SitrepReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    template_path: str = Field(
        ...,
        description="Path or URL to the Word template (.docx) file with Jinja2 placeholders. Supports local paths and remote URLs (http://, https://).",
        title="Template Path",
    )
    groupers: (
        AllGrouper | list[ValueGrouper | TemporalGrouper | SpatialGrouper] | None
    ) = Field(
        None,
        description="            Optional groupers for sorting grouped items. When provided, grouped items\n            are sorted using the grouper's sort_key (e.g., months in calendar order).\n            If not provided, items are sorted alphabetically by filter string.\n            ",
        title="Groupers",
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: WorkflowDetails | None = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Workflow Details",
    )
    time_range: TimeRange | None = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    er_client_name: ErClientName | None = Field(None, title="Data Source")
    get_event_data: GetEventData | None = Field(None, title="Get Illegal Events")
    Process_Events: ProcessEvents | None = Field(
        None,
        alias="Process Events",
        description="Process illegal events: filter, normalize details, generate SITREP table.",
    )
    Generate_Map: GenerateMap | None = Field(
        None,
        alias="Generate Map",
        description="Generate point map of illegal events colored by event type.",
    )
    SITREP_Table_Display: SITREPTableDisplay | None = Field(
        None,
        alias="SITREP Table Display",
        description="Render SITREP table as dashboard widget.",
    )
    sitrep_report: SitrepReport | None = Field(None, title="Create SITREP Report")
    base_map_defs: BaseMapDefs1 | None = None
    persist_sitrep_csv: PersistSitrepCsv | None = None
